###############################################################################
# run_sim.tcl - Launch the lean behavioural simulation (tb_top_lite).
#
# Run inside Vivado after create_project.tcl + build_block_design.tcl have
# succeeded:
#     source scripts/run_sim.tcl
#
# What it does:
#   1. Sets sim_1's top to tb_top_lite (the crash-safe testbench).
#   2. Excludes the BD and its wrapper from simulation so xelab does NOT
#      see two design units named `xil_defaultlib::uproc_top_level` (the
#      one from src/uproc_top_level.vhd and the one auto-generated by the
#      BD).  That duplicate-entity collision is what makes Vivado close
#      with no error message on Windows.
#   3. Caps xsim runtime to 50 us and disables log_all_signals to keep the
#      .wdb file small (prevents the OOM crash on Windows).
#   4. Loads the tb_top_lite.wcfg layout.
#   5. Calls launch_simulation.
###############################################################################

set proj_dir [file normalize "[file dirname [info script]]/.."]

if {[catch {current_project} _]} {
    puts "ERROR: no project open. Run scripts/create_project.tcl first."
    return
}

# 1. Make sure tb_top_lite is in sim_1 and is the top.
if {[llength [get_files -quiet -of [get_filesets sim_1] tb_top_lite.vhd]] == 0} {
    add_files -fileset sim_1 -norecurse "$proj_dir/sim/tb_top_lite.vhd"
    set_property file_type {VHDL 2008} \
        [get_files "$proj_dir/sim/tb_top_lite.vhd"]
}
set_property top tb_top_lite [get_filesets sim_1]

# 2. Exclude the BD + wrapper from simulation if they exist (idempotent;
#    safe to run repeatedly even if build_block_design.tcl already did it).
foreach sim_excluded [list \
    "uproc_top_level.bd" \
    "uproc_top_level_wrapper.vhd" \
] {
    set f [get_files -quiet $sim_excluded]
    if {[llength $f] > 0} {
        set_property used_in_simulation false $f
        puts "run_sim.tcl: excluded $sim_excluded from simulation"
    }
}

# Same idea for the three TEXTIO sim files - confirm they ARE in sim
# (used_in_simulation defaults to true; just be explicit so we don't
# inherit a bad value from a stale project state).
foreach sim_only [list \
    "uproc_top_level.vhd" \
    "irMem.vhd" \
    "dMem.vhd" \
] {
    set f [get_files -quiet $sim_only]
    if {[llength $f] > 0} {
        set_property used_in_simulation true $f
    }
}

update_compile_order -fileset sim_1

# 3. xsim memory-friendly settings
set_property -name {xsim.simulate.runtime}         -value {50us} \
    -objects [get_filesets sim_1]
set_property -name {xsim.simulate.log_all_signals} -value {false} \
    -objects [get_filesets sim_1]

# 4. Make sure the lite waveform layout is the default view
if {[file exists "$proj_dir/sim/tb_top_lite.wcfg"]} {
    if {[llength [get_files -quiet -of [get_filesets sim_1] tb_top_lite.wcfg]] == 0} {
        add_files -fileset sim_1 -norecurse "$proj_dir/sim/tb_top_lite.wcfg"
    }
    set_property xsim.view "$proj_dir/sim/tb_top_lite.wcfg" [get_filesets sim_1]
}

# 5. Launch
launch_simulation
puts ""
puts "===================================================================="
puts "Simulation launched with tb_top_lite (50 us, log_all_signals=false)."
puts ""
puts {If you previously added /tb_top/dut/u_dm/mem or /tb_top/dut/u_ir/mem}
puts {to the wave window, REMOVE them now - they are 1 Mbit BRAM signal}
puts {arrays and tracking them is what crashes xsim.}
puts ""
puts {Look for [TX] and [RX] lines in the Tcl console / sim log.}
puts "===================================================================="
