-------------------------------------------------------------------------------
-- uart.vhd
--
-- 8N1 UART that interfaces to controls (Listing 5.5):
--   * send='1' with charSend valid latches a byte into the TX shift register.
--     The block holds ready='0' until transmission completes, then pulses
--     ready='1' to acknowledge.
--   * On the RX line, a falling edge starts a 10-bit shift; once a full byte
--     is received, charRec is held with the byte and newChar pulses '1' for
--     one en cycle so controls can latch it.
--
-- Bit timing is driven by the bit-rate clock-enable input "en" (typically
-- generated by a clock_div with DIV chosen for 115200 Hz). For RX the start
-- bit is detected on the system clock to avoid missing the falling edge,
-- after which we wait half a bit-time to re-center sampling and then sample
-- on each en pulse.
-------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity uart is
    Generic (
        CLKS_PER_BIT : integer := 1085
    );
    Port (
        clk      : in  std_logic;
        rst      : in  std_logic;

        -- Controls-side interface
        send     : in  std_logic;
        charSend : in  std_logic_vector(7 downto 0);
        ready    : out std_logic;
        newChar  : out std_logic;
        charRec  : out std_logic_vector(7 downto 0);

        -- External pins
        tx       : out std_logic;
        rx       : in  std_logic
    );
end uart;

architecture Behavioral of uart is
    -- TX
    type tx_state_t is (TX_IDLE, TX_RUN);
    signal tx_state  : tx_state_t                 := TX_IDLE;
    signal tx_shift  : std_logic_vector(9 downto 0) := (others => '1');
    signal tx_bitcnt : integer range 0 to 10      := 0;
    signal tx_clkcnt : integer range 0 to CLKS_PER_BIT := 0;
    signal tx_line   : std_logic                  := '1';
    signal ready_int : std_logic                  := '1';

    -- RX
    type rx_state_t is (RX_IDLE, RX_START, RX_DATA_BITS, RX_STOP);
    signal rx_state  : rx_state_t                 := RX_IDLE;
    signal rx_sync0  : std_logic                  := '1';
    signal rx_sync1  : std_logic                  := '1';
    signal rx_shift  : std_logic_vector(7 downto 0) := (others => '0');
    signal rx_bitcnt : integer range 0 to 8       := 0;
    signal rx_clkcnt : integer range 0 to CLKS_PER_BIT := 0;
    signal rx_data   : std_logic_vector(7 downto 0) := (others => '0');
    signal new_pulse : std_logic                  := '0';
begin
    -- Synchroniser for RX
    process(clk)
    begin
        if rising_edge(clk) then
            rx_sync0 <= rx;
            rx_sync1 <= rx_sync0;
        end if;
    end process;

    -- Transmitter: counter-based bit timing using CLKS_PER_BIT.
    process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                tx_state  <= TX_IDLE;
                tx_shift  <= (others => '1');
                tx_bitcnt <= 0;
                tx_clkcnt <= 0;
                tx_line   <= '1';
                ready_int <= '1';
            else
                case tx_state is
                    when TX_IDLE =>
                        tx_line   <= '1';
                        ready_int <= '1';
                        tx_clkcnt <= 0;
                        if send = '1' then
                            -- Frame: stop(1) + data(LSB first 8 bits) + start(0)
                            tx_shift  <= '1' & charSend & '0';
                            tx_bitcnt <= 10;
                            tx_line   <= '0';                  -- start bit
                            tx_shift  <= '1' & charSend & '0';
                            tx_state  <= TX_RUN;
                            ready_int <= '0';
                        end if;

                    when TX_RUN =>
                        -- Drive current LSB of shift register; advance every CLKS_PER_BIT.
                        tx_line <= tx_shift(0);
                        if tx_clkcnt < CLKS_PER_BIT - 1 then
                            tx_clkcnt <= tx_clkcnt + 1;
                        else
                            tx_clkcnt <= 0;
                            tx_shift  <= '1' & tx_shift(9 downto 1);
                            if tx_bitcnt = 1 then
                                tx_state  <= TX_IDLE;
                                ready_int <= '1';
                                tx_bitcnt <= 0;
                            else
                                tx_bitcnt <= tx_bitcnt - 1;
                            end if;
                        end if;

                    when others =>
                        tx_state <= TX_IDLE;
                end case;
            end if;
        end if;
    end process;

    tx    <= tx_line;
    ready <= ready_int;

    -- Receiver: counter-based bit centering using CLKS_PER_BIT.
    process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                rx_state  <= RX_IDLE;
                rx_bitcnt <= 0;
                rx_clkcnt <= 0;
                rx_shift  <= (others => '0');
                rx_data   <= (others => '0');
                new_pulse <= '0';
            else
                new_pulse <= '0';
                case rx_state is
                    when RX_IDLE =>
                        rx_clkcnt <= 0;
                        rx_bitcnt <= 0;
                        if rx_sync1 = '0' then
                            rx_state <= RX_START;
                        end if;

                    when RX_START =>
                        -- Sample mid start bit; if still 0, real start.
                        if rx_clkcnt = (CLKS_PER_BIT - 1) / 2 then
                            if rx_sync1 = '0' then
                                rx_clkcnt <= 0;
                                rx_state  <= RX_DATA_BITS;
                            else
                                rx_state <= RX_IDLE;
                            end if;
                        else
                            rx_clkcnt <= rx_clkcnt + 1;
                        end if;

                    when RX_DATA_BITS =>
                        if rx_clkcnt < CLKS_PER_BIT - 1 then
                            rx_clkcnt <= rx_clkcnt + 1;
                        else
                            rx_clkcnt <= 0;
                            rx_shift  <= rx_sync1 & rx_shift(7 downto 1);
                            if rx_bitcnt = 7 then
                                rx_bitcnt <= 0;
                                rx_state  <= RX_STOP;
                            else
                                rx_bitcnt <= rx_bitcnt + 1;
                            end if;
                        end if;

                    when RX_STOP =>
                        if rx_clkcnt < CLKS_PER_BIT - 1 then
                            rx_clkcnt <= rx_clkcnt + 1;
                        else
                            rx_clkcnt <= 0;
                            rx_data   <= rx_shift;
                            new_pulse <= '1';
                            rx_state  <= RX_IDLE;
                        end if;

                    when others =>
                        rx_state <= RX_IDLE;
                end case;
            end if;
        end if;
    end process;

    charRec <= rx_data;
    newChar <= new_pulse;
end Behavioral;
